services:
  apache:
    build: .
    container_name: apache
    restart: always
    ports:
      - "8084:80" # Accès à l'API via http://localhost:8080
    volumes:
      - ./src:/var/www/html # Monter le répertoire src comme racine du serveur
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3307:3306" # Port MySQL
    environment:
      MYSQL_ROOT_PASSWORD: "root"  # Mot de passe pour l'utilisateur root
      MYSQL_DATABASE: "transagro_db" # Nom de la base de données
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8086:80" # Accès à phpMyAdmin via http://localhost:8086
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data: